shell.prefix("""
set -euo pipefail;
source /home/xuyanbo/mambaforge/etc/profile.d/conda.sh;
conda activate /home/xuyanbo/mambaforge/envs/bioinfo;
""")

configfile: "config.yml"

SAMPLES = list(config["n_reads"].keys())


rule all:
    input:
        expand(f"{config['ds_dir']}/{{sample}}_1.fq.gz", sample=SAMPLES),
        expand(f"{config['ds_dir']}/{{sample}}_2.fq.gz", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_1_val_1.fq.gz", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_2_val_2.fq.gz", sample=SAMPLES),
        expand(f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam", sample=SAMPLES),
        expand(f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam.bai", sample=SAMPLES),
        expand(f"{config['dedup_dir']}/{{sample}}.dedup.bam", sample=SAMPLES),
        expand(f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai", sample=SAMPLES),
        expand(f"{config['dedup_dir']}/{{sample}}.metrics.txt", sample=SAMPLES),

        expand(f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam", sample=SAMPLES),
        expand(f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam.bai", sample=SAMPLES),
        expand(f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CpG.bedGraph", sample=SAMPLES),
        expand(f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CHH.bedGraph", sample=SAMPLES),
        expand(f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CHG.bedGraph", sample=SAMPLES),
        expand(f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext.summary.tsv", sample=SAMPLES),

        expand(f"{config['methyldackel_dir']}/raw_bedGraph/{{sample}}.dedup.mergeContext_CpG.bedGraph", sample=SAMPLES),
        expand(f"{config['methyldackel_dir']}/filter_taps_bedGraph/{{sample}}.minTotal3.filter_taps.bedGraph", sample=SAMPLES),
        expand(f"{config['methyldackel_dir']}/summary/{{sample}}.minTotal3.filter_taps.summary.tsv", sample=SAMPLES),

        expand(f"{config['qc_dir']}/fastqc_raw/{{sample}}_1_fastqc.zip", sample=SAMPLES),
        expand(f"{config['qc_dir']}/fastqc_raw/{{sample}}_2_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.html", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.html", sample=SAMPLES),
        expand(f"{config['qc_dir']}/mapping_efficiency/{{sample}}.mapping_efficiency.tsv", sample=SAMPLES),
        f"{config['qc_dir']}/mapping_efficiency/mapping_efficiency.all.tsv",
        expand(f"{config['qc_dir']}/insert_size_dedup/{{sample}}_insert_size_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/samtools_coverage/{{sample}}.coverage.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/gcbias_dedup/{{sample}}.gc_bias_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/wgs_dedup/{{sample}}_collect_wgs_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/mbias/{{sample}}.mbias.done", sample=SAMPLES),
        f"{config['qc_dir']}/multiqc/multiqc_report.html"


# ============================================================
# 1. Raw FASTQ QC
# ============================================================
rule fastqc_raw:
    input:
        r1 = lambda w: f"{config['raw_dir']}/{w.sample}/{w.sample}_1.fq.gz",
        r2 = lambda w: f"{config['raw_dir']}/{w.sample}/{w.sample}_2.fq.gz"
    output:
        r1_zip = f"{config['qc_dir']}/fastqc_raw/{{sample}}_1_fastqc.zip",
        r2_zip = f"{config['qc_dir']}/fastqc_raw/{{sample}}_2_fastqc.zip"
    threads: 8
    resources:
        mem_mb = 32000
    params:
        outdir = f"{config['qc_dir']}/fastqc_raw"
    shell:
        r"""
        mkdir -p {params.outdir}
        module load fastqc/0.12.1

        fastqc -t {threads} \
            -o {params.outdir} \
            {input.r1} {input.r2}
        """


# ----------------------------
# ============================================================
# 2. Downsample
# ============================================================
rule downsample:
    input:
        r1 = lambda w: f"{config['raw_dir']}/{w.sample}/{w.sample}_1.fq.gz",
        r2 = lambda w: f"{config['raw_dir']}/{w.sample}/{w.sample}_2.fq.gz"
    output:
        r1 = f"{config['ds_dir']}/{{sample}}_1.fq.gz",
        r2 = f"{config['ds_dir']}/{{sample}}_2.fq.gz"
    threads: 8
    resources:
        mem_mb = 32000
    params:
        n = lambda w: int(config["n_reads"][w.sample]),
        seed = 100
    shell:
        r"""
        mkdir -p {config[ds_dir]}

        rasusa reads {input.r1} {input.r2} \
            -n {params.n} \
            -s {params.seed} \
            -o {output.r1} \
            -o {output.r2}
        """


# ============================================================
# 3. Trim and trimmed FastQC
# ============================================================
rule trim:
    input:
        r1 = f"{config['ds_dir']}/{{sample}}_1.fq.gz",
        r2 = f"{config['ds_dir']}/{{sample}}_2.fq.gz"
    output:
        r1 = f"{config['trim_dir']}/{{sample}}_1_val_1.fq.gz",
        r2 = f"{config['trim_dir']}/{{sample}}_2_val_2.fq.gz",
        r1_fastqc_zip = f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.zip",
        r2_fastqc_zip = f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.zip",
        r1_fastqc_html = f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.html",
        r2_fastqc_html = f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.html"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[trim_dir]}
        module load trim_galore/0.6.10
        module load fastqc/0.12.1

        trim_galore --paired --cores {threads} --length 35 --fastqc \
            --gzip \
            -o {config[trim_dir]} \
            {input.r1} {input.r2}
        """


rule align:
    input:
        r1 = f"{config['trim_dir']}/{{sample}}_1_val_1.fq.gz",
        r2 = f"{config['trim_dir']}/{{sample}}_2_val_2.fq.gz"
    output:
        bam = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam",
        bai = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam.bai"
    threads:20
    resources:
        mem_mb = 80000
    params:
        ref = config["reference_fasta"]
    shell:
        r"""
        mkdir -p {config[map_dir]}

        module load samtools/1.18

        bwa-mem2 mem \
            -t {threads} \
            {params.ref} \
            {input.r1} \
            {input.r2} \
        | samtools sort -@ {threads} -o {output.bam} -

        samtools index -@ {threads} {output.bam}
        """


# ----------------------------
# Mapping efficiency:
# ----------------------------
rule mapping_efficiency:
    input:
        r1 = f"{config['trim_dir']}/{{sample}}_1_val_1.fq.gz",
        bam = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam",
        bai = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam.bai"
    output:
        f"{config['qc_dir']}/mapping_efficiency/{{sample}}.mapping_efficiency.tsv"
    threads: 8
    resources:
        mem_mb = 32000
    params:
        exclude_flags = 2308
    shell:
        r"""
        mkdir -p {config[qc_dir]}/mapping_efficiency
        module load samtools/1.18

        trimmed_read1=$(zcat -f {input.r1} | awk 'END{{print NR/4}}')
        aligned_read1=$(samtools view -@ {threads} -c \
            -f 64 \
            -F {params.exclude_flags} \
            {input.bam})

        awk -v sample="{wildcards.sample}" \
            -v trimmed="$trimmed_read1" \
            -v aligned="$aligned_read1" \
        'BEGIN{{
            OFS="\t";
            eff = (trimmed > 0 ? aligned / trimmed : "NA");
            print "sample", "trimmed_read1", "aligned_primary_read1", "mapping_efficiency";
            print sample, trimmed, aligned, eff;
        }}' > {output}
        """


rule mapping_efficiency_all:
    input:
        expand(f"{config['qc_dir']}/mapping_efficiency/{{sample}}.mapping_efficiency.tsv", sample=SAMPLES)
    output:
        f"{config['qc_dir']}/mapping_efficiency/mapping_efficiency.all.tsv"
    shell:
        r"""
        mkdir -p {config[qc_dir]}/mapping_efficiency
        head -n 1 {input[0]} > {output}
        for f in {input}; do
            tail -n +2 $f
        done >> {output}
        """


# ----------------------------
# ============================================================
# 5. Spike-in conversion QC from pre-dedup BAM
# ============================================================
rule extract_spikein_prededup_bam:
    input:
        bam = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam",
        bai = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam.bai",
        fai = config["spike_in_fai"]
    output:
        bam = f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam",
        bai = f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam.bai"
    threads: 8
    resources:
        mem_mb = 32000
    params:
        spike1 = "2kb_2",
        spike2 = "2kb_3|Unmodified"
    shell:
        r"""
        mkdir -p {config[qc_dir]}/spikein_prededup_bam
        module load samtools/1.18

        samtools view -@ {threads} -b \
            -L <(
                awk -v s1="{params.spike1}" -v s2="{params.spike2}" 'BEGIN{{OFS="\t"}}
                $1 == s1 || $1 == s2 {{
                    print $1, 0, $2
                }}' {input.fai}
            ) \
            {input.bam} \
        | samtools sort -@ {threads} -o {output.bam} -

        samtools index -@ {threads} {output.bam}
        """


rule methyl_call_spikein_prededup:
    input:
        bam = f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam",
        bai = f"{config['qc_dir']}/spikein_prededup_bam/{{sample}}.prededup.spikein.bam.bai",
        ref = config["spike_in_fasta"],
        fai = config["spike_in_fai"]
    output:
        cpg = f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CpG.bedGraph",
        chg = f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CHG.bedGraph",
        chh = f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext_CHH.bedGraph",
        summary = f"{config['qc_dir']}/spikein_prededup_methyldackel/{{sample}}.prededup.spikein.mergeContext.summary.tsv"
    threads: 8
    resources:
        mem_mb = 32000
    params:
        spike1 = "2kb_2",
        spike2 = "2kb_3|Unmodified"
    shell:
        r"""
        mkdir -p {config[qc_dir]}/spikein_prededup_methyldackel
        module load MethylDackel/0.6.1

        MethylDackel extract \
            -@ {threads} \
            -q 10 \
            -p 13 \
            --mergeContext \
            --CHG \
            --CHH \
            --OT 5,136,5,136 \
            --OB 5,136,5,136 \
            -l <(
                awk -v s1="{params.spike1}" -v s2="{params.spike2}" 'BEGIN{{OFS="\t"}}
                $1 == s1 || $1 == s2 {{
                    print $1, 0, $2
                }}' {input.fai}
            ) \
            -o {config[qc_dir]}/spikein_prededup_methyldackel/{wildcards.sample}.prededup.spikein.mergeContext \
            {input.ref} \
            {input.bam}

        conv_2kb_2=`cat {output.cpg} | awk -F "\t" '$1=="2kb_2" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (mC+uC>0) printf("%.4f", mC/(mC+uC)); else printf("NA")}}'`
        unconv_2kb_2=`cat {output.cpg} | awk -F "\t" '$1=="2kb_2" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (mC+uC>0) printf("%.4f", uC/(mC+uC)); else printf("NA")}}'`
        cov_2kb_2=`cat {output.cpg} | awk -F "\t" '$1=="2kb_2" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (NR>0) printf("%.4f", (mC+uC)/NR); else printf("NA")}}'`

        conv_2kb_3=`cat {output.cpg} {output.chg} {output.chh} | awk -F "\t" '$1=="2kb_3|Unmodified" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (mC+uC>0) printf("%.4f", mC/(mC+uC)); else printf("NA")}}'`
        unconv_2kb_3=`cat {output.cpg} {output.chg} {output.chh} | awk -F "\t" '$1=="2kb_3|Unmodified" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (mC+uC>0) printf("%.4f", uC/(mC+uC)); else printf("NA")}}'`
        cov_2kb_3=`cat {output.cpg} {output.chg} {output.chh} | awk -F "\t" '$1=="2kb_3|Unmodified" && $5+$6>0' | awk -F "\t" '{{mC+=$6;uC+=$5}}END{{if (NR>0) printf("%.4f", (mC+uC)/NR); else printf("NA")}}'`

        echo -e "sample\tconversion_2kb_2\tunconversion_2kb_2\tcoverage_2kb_2\tconversion_2kb_3_unmodified\tunconversion_2kb_3_unmodified\tcoverage_2kb_3_unmodified" > {output.summary}
        echo -e "{wildcards.sample}\t${{conv_2kb_2}}\t${{unconv_2kb_2}}\t${{cov_2kb_2}}\t${{conv_2kb_3}}\t${{unconv_2kb_3}}\t${{cov_2kb_3}}" >> {output.summary}
        """

# ============================================================
# 6. Picard dedup
# ============================================================
rule dedup:
    input:
        bam = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam",
        bai = f"{config['map_dir']}/{{sample}}.bwa_mem2.sorted.bam.bai"
    output:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai",
        metrics = f"{config['dedup_dir']}/{{sample}}.metrics.txt"
    threads:20
    resources:
        mem_mb = 80000
    shell:
        r"""
        mkdir -p {config[dedup_dir]}
        module load samtools/1.18

        picard -Xmx72g AddOrReplaceReadGroups \
            I={input.bam} \
            O={config[dedup_dir]}/{wildcards.sample}.rg.temp.bam \
            RGID={wildcards.sample} \
            RGLB=lib1 \
            RGPL=ILLUMINA \
            RGPU=unit1 \
            RGSM={wildcards.sample} \
            VALIDATION_STRINGENCY=SILENT

        picard -Xmx72g MarkDuplicates \
            I={config[dedup_dir]}/{wildcards.sample}.rg.temp.bam \
            O={output.bam} \
            M={output.metrics} \
            REMOVE_DUPLICATES=true \
            ASSUME_SORT_ORDER=coordinate \
            VALIDATION_STRINGENCY=SILENT

        samtools index -@ {threads} {output.bam}
        rm -f {config[dedup_dir]}/{wildcards.sample}.rg.temp.bam
        """


# ============================================================
# 7. Genome MethylDackel and TAPS-direction bedGraph
# ============================================================
rule methyl_call_genome_dedup:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai",
        ref = config["reference_fasta"]
    output:
        raw = f"{config['methyldackel_dir']}/raw_bedGraph/{{sample}}.dedup.mergeContext_CpG.bedGraph"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[methyldackel_dir]}/raw_bedGraph
        module load MethylDackel/0.6.1

        MethylDackel extract \
            -@ {threads} \
            -q 10 \
            -p 13 \
            --mergeContext \
            --OT 5,136,5,136 \
            --OB 5,136,5,136 \
            -o {config[methyldackel_dir]}/raw_bedGraph/{wildcards.sample}.dedup.mergeContext \
            {input.ref} \
            {input.bam}

        """


rule filter_and_convert_taps:
    input:
        raw = f"{config['methyldackel_dir']}/raw_bedGraph/{{sample}}.dedup.mergeContext_CpG.bedGraph",
        dbsnp = config["dbsnp_bed"],
        centromere = config["centromere_bed"],
        blacklist = config["blacklist_bed"]
    output:
        taps = f"{config['methyldackel_dir']}/filter_taps_bedGraph/{{sample}}.minTotal3.filter_taps.bedGraph",
        summary = f"{config['methyldackel_dir']}/summary/{{sample}}.minTotal3.filter_taps.summary.tsv"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[methyldackel_dir]}/filter_taps_bedGraph
        mkdir -p {config[methyldackel_dir]}/summary
        module load bedtools/2.31.0

        cat {input.raw} | awk 'BEGIN{{OFS="\t"}}
        $1 !~ /^(track|#)/ &&
        $1 ~ /^chr([1-9]|1[0-9]|2[0-2])$/ &&
        ($5 + $6) >= 3 {{
            print $1,$2,$3,100-$4,$6,$5+$6
        }}' | sort -k1,1 -k2,2n | \
            bedtools intersect -a - -b <(
                cat {input.dbsnp} {input.centromere} {input.blacklist} \
                | grep -P '^chr([1-9]|1[0-9]|2[0-2])\t' \
                | cut -f1-3 \
                | sort -k1,1 -k2,2n
            ) -v -sorted > {output.taps}

        awk -v sample="{wildcards.sample}" 'BEGIN{{FS=OFS="\t"; n=0; taps=0; total=0}}
        {{
            n++;
            taps += $5;
            total += $6;
        }}
        END{{
            print "sample", "covered_cpg_minTotal3", "total_taps_positive_count", "total_informative_count", "weighted_taps_readout";
            if (total > 0) {{
                print sample, n, taps, total, taps/total;
            }} else {{
                print sample, n, taps, total, "NA";
            }}
        }}' {output.taps} > {output.summary}
        """


rule insert_size_dedup:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai"
    output:
        metrics = f"{config['qc_dir']}/insert_size_dedup/{{sample}}_insert_size_metrics.txt",
        chart = f"{config['qc_dir']}/insert_size_dedup/{{sample}}_insert_size.pdf"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[qc_dir]}/insert_size_dedup

        picard -Xmx72g CollectInsertSizeMetrics \
            I={input.bam} \
            O={output.metrics} \
            H={output.chart} \
            M=0.1 \
            VALIDATION_STRINGENCY=SILENT
        """


rule samtools_coverage:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai"
    output:
        coverage = f"{config['qc_dir']}/samtools_coverage/{{sample}}.coverage.txt"
    threads: 4
    resources:
        mem_mb = 16000
    shell:
        r"""
        mkdir -p {config[qc_dir]}/samtools_coverage
        module load samtools/1.18

        samtools coverage {input.bam} > {output.coverage}
        """


rule gc_bias_dedup:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai",
        ref = config["reference_fasta"]
    output:
        metrics = f"{config['qc_dir']}/gcbias_dedup/{{sample}}.gc_bias_metrics.txt",
        chart = f"{config['qc_dir']}/gcbias_dedup/{{sample}}.gc_bias.pdf",
        summary = f"{config['qc_dir']}/gcbias_dedup/{{sample}}.gc_bias_summary.txt"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[qc_dir]}/gcbias_dedup

        picard -Xmx72g CollectGcBiasMetrics \
            I={input.bam} \
            O={output.metrics} \
            CHART={output.chart} \
            S={output.summary} \
            R={input.ref} \
            VALIDATION_STRINGENCY=SILENT
        """


rule wgs_metrics_dedup:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai",
        ref = config["reference_fasta"]
    output:
        metrics = f"{config['qc_dir']}/wgs_dedup/{{sample}}_collect_wgs_metrics.txt"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[qc_dir]}/wgs_dedup

        picard -Xmx72g CollectWgsMetrics \
            I={input.bam} \
            O={output.metrics} \
            R={input.ref} \
            VALIDATION_STRINGENCY=SILENT
        """


rule methyl_mbias_qc:
    input:
        bam = f"{config['dedup_dir']}/{{sample}}.dedup.bam",
        bai = f"{config['dedup_dir']}/{{sample}}.dedup.bam.bai",
        ref = config["reference_fasta"]
    output:
        touch(f"{config['qc_dir']}/mbias/{{sample}}.mbias.done")
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        r"""
        mkdir -p {config[qc_dir]}/mbias
        module load MethylDackel/0.6.1

        MethylDackel mbias \
            -@ {threads} \
            -q 10 \
            -p 13 \
            {input.ref} \
            {input.bam} \
            {config[qc_dir]}/mbias/{wildcards.sample}.mbias
        """


# ============================================================
# 9. MultiQC
# ============================================================
rule multiqc:
    input:
        expand(f"{config['qc_dir']}/fastqc_raw/{{sample}}_1_fastqc.zip", sample=SAMPLES),
        expand(f"{config['qc_dir']}/fastqc_raw/{{sample}}_2_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.zip", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_1_val_1_fastqc.html", sample=SAMPLES),
        expand(f"{config['trim_dir']}/{{sample}}_2_val_2_fastqc.html", sample=SAMPLES),
        expand(f"{config['qc_dir']}/mapping_efficiency/{{sample}}.mapping_efficiency.tsv", sample=SAMPLES),
        f"{config['qc_dir']}/mapping_efficiency/mapping_efficiency.all.tsv",
        expand(f"{config['qc_dir']}/insert_size_dedup/{{sample}}_insert_size_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/samtools_coverage/{{sample}}.coverage.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/gcbias_dedup/{{sample}}.gc_bias_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/wgs_dedup/{{sample}}_collect_wgs_metrics.txt", sample=SAMPLES),
        expand(f"{config['qc_dir']}/mbias/{{sample}}.mbias.done", sample=SAMPLES)
    output:
        f"{config['qc_dir']}/multiqc/multiqc_report.html"
    params:
        outdir = f"{config['qc_dir']}/multiqc"
    shell:
        r"""
        mkdir -p {params.outdir}
        module load multiqc/1.28

        multiqc {config[qc_dir]} {config[trim_dir]} {config[dedup_dir]} {config[methyldackel_dir]} \
            -o {params.outdir} \
            -f
        """
